name: Bug
description: Format/logic error
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce?
  - type: textarea
    id: expect
    attributes:
      label: What did you expect?
