name: Feature
description: Request or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
  - type: textarea
    id: how
    attributes:
      label: Proposed approach
