name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-addendum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate README addendum formatting
        run: |
          python - <<'EOF'
import re, sys
path = 'README.md'
with open(path, encoding='utf-8') as f:
    lines = f.readlines()
inside_code = False
errors = []
for i, line in enumerate(lines):
    stripped = line.rstrip('\n')
    if stripped.startswith('```'):
        inside_code = not inside_code
    if not inside_code:
        # check for horizontal rule lines: U+2500 repeated 12-16 times or Markdown hr '---'
        if re.fullmatch(r'\u2500{12,16}', stripped):
            plus_line = lines[i+1].strip() if i+1 < len(lines) else ''
            blank_line = lines[i+2].strip() if i+2 < len(lines) else ''
            if plus_line != '+':
                errors.append(f'Missing plus sign after rule on line {i+1}')
            if blank_line != '':
                errors.append(f'Missing blank line after plus on line {i+2}')
if errors:
    for error in errors:
        print(error)
    sys.exit(1)
EOF

      - name: Verify repository structure
        run: |
          test -f SYSTEM.txt && echo "SYSTEM.txt exists"
          test -f RUNTIME.md && echo "RUNTIME.md exists"
          test -f templates/custom_instructions.md && echo "Templates present"
